"""Generate docs/specs/<concept>.yaml -- machine-readable formal definitions."""
import pathlib
import textwrap

OUT = pathlib.Path("docs/specs")
OUT.mkdir(parents=True, exist_ok=True)

HEADER = """# Formal specification -- {title}
# Auto-generated by tools/generate_specs.py; edit that file, not this one.
# Schema: docs/specs/_schema.yaml
"""

SPECS = {
"ict_displacement": dict(
    concept="ICT Displacement Candle", source="ICT_Concepts_LuxAlgo.pine",
    source_section="1.4", module="signals/ict_signals.py::detect_displacement",
    signals=[("ict_displacement_bullish", 1), ("ict_displacement_bearish", -1)],
    definition="""
      body_i        = abs(close_i - open_i)
      mean_body_i   = SMA(body, length)_i
      mx_i          = max(close_i, open_i);  mn_i = min(close_i, open_i)
      clean_body_i  = (high_i - mx_i < body_i * perc_body)
                      AND (mn_i - low_i < body_i * perc_body)
      bullish_i     = body_i > mean_body_i AND clean_body_i AND close_i > open_i
      bearish_i     = body_i > mean_body_i AND clean_body_i AND close_i < open_i
    """,
    params=[("length","int",5,"3..10","Body-average lookback (Pine `len`)"),
            ("perc_body","float",0.36,"0.05..0.90","Max wick fraction of body; hard-coded `perc_Body` in source")],
    causal="Uses only bars <= i. SMA window is trailing and includes bar i.",
    min_occurrences=200,
    notes="Directional by construction; no confirmation lag.",
),
"ict_fvg": dict(
    concept="ICT Fair Value Gap", source="ICT_Concepts_LuxAlgo.pine",
    source_section="1.6", module="signals/ict_signals.py::detect_fvg",
    signals=[("ict_fvg_bullish_formed", 1), ("ict_fvg_bearish_formed", -1)],
    definition="""
      # FORMATION (tradeable event, fires at bar i)
      bullish_i = displacement_bullish_{i-1} AND low_i  > high_{i-2}
      bearish_i = displacement_bearish_{i-1} AND high_i < low_{i-2}

      # GAP REGION (continuous feature)
      bullish gap region = [high_{i-2}, low_i]      # lower, upper
      bearish gap region = [high_i,     low_{i-2}]

      # FILL (OUTCOME LABEL -- NOT an entry signal)
      filled_i = exists k in (i, i+N] such that
                   bullish: low_k  < high_{i-2}
                   bearish: high_k > low_{i-2}
    """,
    params=[("mode","str","FVG","FVG|IFVG","IFVG is LuxAlgo's non-standard inversion (Ambiguity A1)"),
            ("fill_window_N","int",60,"1..250","Bars after formation in which a fill counts; default = longest holding period")],
    causal=("Formation uses only bars <= i. The fill column is forward-looking "
            "BY DESIGN and is emitted with a `_label` suffix, excluded from "
            "EVENT_REGISTRY. It was previously emitted as a tradeable event."),
    min_occurrences=500,
    notes=("Gap-region columns were named `_top`/`_bottom` with inverted meaning; "
           "renamed `_lower`/`_upper`. See docs/specs/ict_bpr.yaml."),
),
"ict_bpr": dict(
    concept="ICT Balanced Price Range", source="ICT_Concepts_LuxAlgo.pine",
    source_section="1.7", module="signals/ict_signals.py::detect_bpr",
    signals=[("ict_bpr_bullish", 1), ("ict_bpr_bearish", -1)],
    definition="""
      A = most recent bullish FVG region [a_lo, a_hi]
      B = most recent bearish FVG region [b_lo, b_hi]
      overlap_i = max(a_lo, b_lo) < min(a_hi, b_hi)
      bullish_i = overlap_i AND fvg_bullish_formed_i
      bearish_i = overlap_i AND fvg_bearish_formed_i
    """,
    params=[],
    causal="Both regions are carried forward from bars <= i.",
    min_occurrences=50,
    notes=("DEFECT FIXED: the prior condition `(up_bot < dn_top) AND (dn_bot < up_bot)` "
           "was written against inverted column names and reduces to "
           "`dn_upper < dn_lower`, which is unsatisfiable. Both signals were "
           "identically False for every ticker and bar, and melt_events drops "
           "all-False columns silently, so the concept vanished from the study "
           "with no error."),
),
"ict_order_block": dict(
    concept="ICT Order Block", source="ICT_Concepts_LuxAlgo.pine",
    source_section="1.3", module="signals/ict_signals.py::detect_order_blocks",
    signals=[("ict_ob_bullish_formed", 1), ("ict_ob_bearish_formed", -1),
             ("ict_ob_bullish_mitigated", -1), ("ict_ob_bearish_mitigated", 1)],
    definition="""
      # Reference swing: the MOST RECENT confirmed swing only (Pine `swings()`
      # replaces its single `var swing` object; older unbroken swings are
      # forgotten, not queued).
      top_level = most recent confirmed swing high, at bar top_bar
      btm_level = most recent confirmed swing low,  at bar btm_bar

      # FORMATION at the breaking bar i
      bullish_formed_i = (not top_crossed) AND close_i > top_level
        -> block candle j = argmin over [top_bar .. i] of min_src
        -> block region   = [min_src_j, max_src_j]
      bearish_formed_i = (not btm_crossed) AND close_i < btm_level
        -> block candle j = argmax over [btm_bar .. i] of max_src

      # MITIGATION (a formed block being violated)
      bullish_mitigated_i = min(close_i, open_i) < block_bottom
      bearish_mitigated_i = max(close_i, open_i) > block_top
    """,
    params=[("length","int",10,">=3","Swing lookback (Pine `length`)"),
            ("use_body","bool",True,"true|false","Use candle bodies vs wicks for the block region"),
            ("ob_max_retained","int",200,"10..1000","Active-block cap; source is uncapped")],
    causal=("Swing points come from extract_swing_points, which stamps the "
            "confirmation bar and reads price from `size` bars earlier. "
            "Formation fires on the break bar. All inputs <= i."),
    min_occurrences=200,
    notes=("Mitigation is scored as the OPPOSITE direction to formation: a "
           "bullish order block failing is bearish evidence. The prior "
           "name-substring direction heuristic assigned +1 to "
           "`ict_ob_bullish_mitigated` because the name contains 'bullish'."),
),
"ict_liquidity_sweep": dict(
    concept="ICT Liquidity Sweep (stop run + rejection)",
    source="ICT_Concepts_LuxAlgo.pine + standard ICT definition",
    source_section="1.8", module="signals/ict_signals.py::detect_liquidity_sweep",
    signals=[("ict_sweep_buyside_bearish", -1), ("ict_sweep_sellside_bullish", 1)],
    definition="""
      L = most recent confirmed swing high (buy-side) / low (sell-side)

      # (X) PENETRATION at bar j -- the stop run
      buyside:  high_j > L + X * ATR_j
      sellside: low_j  < L - X * ATR_j

      # (Y,Z) RECLAIM at bar k, j < k <= j + Z -- the rejection
      buyside:  close_k < L - Y * ATR_k   -> ict_sweep_buyside_bearish_k
      sellside: close_k > L + Y * ATR_k   -> ict_sweep_sellside_bullish_k

      Event is stamped on bar k. If no reclaim occurs within Z bars the
      penetration is discarded.
    """,
    params=[("X  sweep_penetration_atr","float",0.25,"0.05..1.00","Minimum penetration beyond the level, in ATR"),
            ("Y  sweep_reclaim_frac","float",0.0,"0.0..1.0","Reclaim depth past the level, in ATR"),
            ("Z  sweep_confirm_bars","int",3,"1..10","Bars allowed between penetration and reclaim"),
            ("sweep_atr_len","int",14,"5..50","ATR length"),
            ("sweep_swing_len","int",10,"3..50","Swing lookback for the reference level")],
    causal="Event fires on the reclaim bar k using only bars <= k.",
    min_occurrences=100,
    notes=("REPLACES the prior `*_swept` logic, which fired when `close > "
           "pool_bottom` -- price merely ENTERING the pool, with no rejection "
           "leg. That is a breakout, not a sweep, and made the 'swept' signals "
           "near-duplicates of pool formation. The old columns are retained "
           "under their original names for continuity."),
),
"ict_opening_gap": dict(
    concept="ICT New Week / New Day Opening Gap",
    source="ICT_Concepts_LuxAlgo.pine", source_section="1.9",
    module="signals/ict_signals.py::detect_nwog_ndog",
    signals=[("ict_nwog_gap_up", 1), ("ict_nwog_gap_down", -1),
             ("ict_ndog_gap_up", 1), ("ict_ndog_gap_down", -1)],
    definition="""
      gap_i      = open_i - close_{i-1}
      material_i = abs(gap_i) >= gap_min_atr * ATR(gap_atr_len)_{i-1}
      week_open_i = dayofweek_i <= dayofweek_{i-1}      # calendar week rolled over

      nwog_up_i   = enabled_nwog AND material_i AND week_open_i AND gap_i > 0
      nwog_down_i = enabled_nwog AND material_i AND week_open_i AND gap_i < 0
      ndog_up_i   = enabled_ndog AND material_i AND gap_i > 0
      ndog_down_i = enabled_ndog AND material_i AND gap_i < 0
    """,
    params=[("gap_min_atr","float",0.10,"0.0..2.0","Minimum |gap| as a multiple of ATR"),
            ("gap_atr_len","int",14,"5..50","ATR length"),
            ("nwog_enabled","bool",True,"true|false","Source default: on"),
            ("ndog_enabled","bool",False,"true|false","Source default: off")],
    causal="Uses close_{i-1}, open_i and ATR through bar i-1 only.",
    min_occurrences=100,
    notes=("DEFECT FIXED: `ict_ndog_formed` was `True` on essentially every "
           "bar -- 1,946,675 events, 45% of the entire event table -- because "
           "it tested only that open and prior close were non-null. It also "
           "ignored the enable flags, and carried an unsigned gap size, so the "
           "melted event had direction 0 and was coerced long."),
),
"ict_market_structure": dict(
    concept="ICT Market Structure Shift and Break of Structure",
    source="ICT_Concepts_LuxAlgo.pine", source_section="1.1 + 1.2",
    module="signals/ict_signals.py::detect_mss_bos",
    signals=[("ict_mss_bullish", 1), ("ict_mss_bearish", -1),
             ("ict_bos_bullish", 1), ("ict_bos_bearish", -1)],
    definition="""
      # Zigzag vertices from CONFIRMED pivots (ta.pivothigh/low, right = 1),
      # so a vertex is only usable one bar after the pivot bar itself.
      on confirmed pivot high at bar i:  push/extend an up-vertex at high[i-1]
      on confirmed pivot low  at bar i:  push/extend a down-vertex at low[i-1]

      swing_high = price of the most recent up-vertex
      swing_low  = price of the most recent down-vertex

      # MSS -- the first break that REVERSES the prevailing direction
      mss_bullish_i = close_i > swing_high AND dir < +1   -> dir := +1
      mss_bearish_i = close_i < swing_low  AND dir > -1   -> dir := -1

      # BOS -- a subsequent break CONTINUING the established direction, against
      # a level not already consumed by an MSS or an earlier BOS
      bos_bullish_i = dir == +1 AND close_i > swing_high
                      AND swing_high not in {last_bos_level, last_mss_level}
      bos_bearish_i = mirror
    """,
    params=[("mss_pivot_len","int",5,"3..10","Pivot left-lookback (Pine `len`); right lookback is 1")],
    causal=("Vertices come from pivots confirmed with right = 1 and priced at "
            "bar i-1, so bar i uses only bars <= i. The dir/level state machine "
            "is sequential and reads no future bar."),
    min_occurrences=500,
    notes=("MSS and BOS are distinguished only by the state machine: the same "
           "geometric break is an MSS if it reverses `dir` and a BOS if it "
           "continues it. The de-duplication against `last_bos_level` and "
           "`last_mss_level` prevents one swing level from emitting repeatedly "
           "as price oscillates across it."),
),
"ict_volume_imbalance": dict(
    concept="ICT Volume Imbalance", source="ICT_Concepts_LuxAlgo.pine",
    source_section="1.5", module="signals/ict_signals.py::detect_volume_imbalance",
    signals=[("ict_volume_imbalance_bullish", 1), ("ict_volume_imbalance_bearish", -1)],
    definition="""
      mx_i = max(close_i, open_i);  mn_i = min(close_i, open_i)

      bullish_i = open_i  > close_{i-1}      # gap up on the open
                  AND high_{i-1} > low_i     # wicks still overlap
                  AND close_i > close_{i-1}
                  AND open_i  > open_{i-1}
                  AND high_{i-1} < mn_i      # prior high below this body

      bearish_i = open_i  < close_{i-1}
                  AND low_{i-1} < high_i
                  AND close_i < close_{i-1}
                  AND open_i  < open_{i-1}
                  AND low_{i-1} > mx_i
    """,
    params=[],
    causal="Uses bars i and i-1 only.",
    min_occurrences=1000,
    notes=("A volume imbalance is the body-level gap that remains when two "
           "candles' wicks overlap but their bodies do not -- distinct from a "
           "Fair Value Gap, which requires a true 3-bar wick-to-wick void."),
),
"ict_liquidity_pool": dict(
    concept="ICT Liquidity Pool (clustered equal highs/lows)",
    source="ICT_Concepts_LuxAlgo.pine", source_section="1.8",
    module="signals/ict_signals.py::detect_liquidity",
    signals=[("ict_liquidity_buyside_pool_formed", 1),
             ("ict_liquidity_sellside_pool_formed", -1),
             ("ict_liquidity_buyside_swept", 1),
             ("ict_liquidity_sellside_swept", -1)],
    definition="""
      a    = 10 / margin
      band = ATR(liquidity_atr_len)_i / a

      # POOL FORMATION, on a confirmed pivot at bar i with price p
      cluster = { q : q is a same-direction vertex in the last 50
                      AND |q - p| < band }
      pool forms iff |cluster| > liquidity_min_cluster
        mid    = (min(cluster) + max(cluster)) / 2
        region = [mid - band, mid + band]

      # SWEEP (legacy semantics, retained for comparison -- see notes)
      buyside_swept_i  = close_i > region.bottom, first time only
      sellside_swept_i = close_i < region.top,    first time only
    """,
    params=[("mss_pivot_len","int",5,"3..10","Pivot lookback feeding the vertex list"),
            ("liquidity_margin","float",4.0,"1.0..20.0","Band width divisor; a = 10/margin"),
            ("liquidity_atr_len","int",10,"5..50","ATR length for the band"),
            ("liquidity_min_cluster","int",2,"1..10","Pivots required in-band, exclusive (> not >=)")],
    causal="Pivots carry their confirmation lag; ATR and the vertex list are trailing.",
    min_occurrences=500,
    notes=("The `*_swept` signals fire when price merely ENTERS the pool region, "
           "with no rejection leg -- that is a breakout, not a sweep, which is "
           "why they behave almost identically to pool formation. They are "
           "retained under their original names so the reformulation is visible "
           "as a comparison; the prospective replacement is "
           "docs/specs/ict_liquidity_sweep.yaml. Also note the cluster test "
           "contains a redundant conjunct in the source translation "
           "(`|q-p| < band` AND `p-band < q < p+band` are the same condition)."),
),
"smc_structure": dict(
    concept="SMC Break of Structure / Change of Character",
    source="SMC_Concepts_LuxAlgo.pine", source_section="2.2",
    module="signals/smc_signals.py::_structure_and_ob",
    signals=[("smc_swing_bos_bullish",1),("smc_swing_bos_bearish",-1),
             ("smc_swing_choch_bullish",1),("smc_swing_choch_bearish",-1),
             ("smc_internal_bos_bullish",1),("smc_internal_bos_bearish",-1),
             ("smc_internal_choch_bullish",1),("smc_internal_choch_bearish",-1)],
    definition="""
      leg(size):  new_leg_high_i = high_{i-size} > highest(high, size)_i
                  new_leg_low_i  = low_{i-size}  < lowest(low, size)_i
      swing high level H set on a bearish-leg transition, price = high_{i-size}
      swing low  level L set on a bullish-leg transition, price = low_{i-size}

      crossover_i  = close_i > H AND close_{i-1} <= H
      crossunder_i = close_i < L AND close_{i-1} >= L

      bullish break_i = crossover_i AND (not H already crossed)
        -> CHoCH if prior trend bias was BEARISH, else BOS
      bearish break_i = crossunder_i AND (not L already crossed)
        -> CHoCH if prior trend bias was BULLISH, else BOS
    """,
    params=[("swing_len","int",50,">=10","Swing scale (Pine `swingsLengthInput`)"),
            ("internal_len","int",5,"3..15","Internal scale; hard-coded in source"),
            ("internal_filter_confluence","bool",False,"true|false","Wick-asymmetry filter on internal breaks")],
    causal="leg() compares high_{i-size} against a trailing window ending at i.",
    min_occurrences=200,
    notes="Swing and internal scales run through one shared implementation.",
),
"smc_order_block": dict(
    concept="SMC Order Block", source="SMC_Concepts_LuxAlgo.pine",
    source_section="2.3", module="signals/smc_signals.py::_structure_and_ob",
    signals=[("smc_swing_ob_bullish_formed",1),("smc_swing_ob_bearish_formed",-1),
             ("smc_swing_ob_bullish_mitigated",-1),("smc_swing_ob_bearish_mitigated",1),
             ("smc_internal_ob_bullish_formed",1),("smc_internal_ob_bearish_formed",-1),
             ("smc_internal_ob_bullish_mitigated",-1),("smc_internal_ob_bearish_mitigated",1)],
    definition="""
      # Volatility-adjusted source (guards against one outlier bar)
      high_vol_bar_i = (high_i - low_i) >= 2 * ATR(ob_atr_len)_i
      parsed_high_i  = low_i  if high_vol_bar_i else high_i
      parsed_low_i   = high_i if high_vol_bar_i else low_i

      # FORMATION on a structure break at bar i (see smc_structure)
      bullish: j = argmax parsed_high over [pivot_bar .. i]
      bearish: j = argmin parsed_low  over [pivot_bar .. i]
      block region = [parsed_low_j, parsed_high_j]

      # MITIGATION (High/Low mode, the source default)
      bullish_mitigated_i = low_i  < block_bottom
      bearish_mitigated_i = high_i > block_top
    """,
    params=[("ob_atr_len","int",200,"20..400","Volatility measure length"),
            ("ob_filter_mode","str","Atr","Atr|Cumulative Mean Range",""),
            ("ob_mitigation_mode","str","High/Low","Close|High/Low",""),
            ("ob_max_retained","int",100,"10..500","Matches the source array cap")],
    causal="All inputs <= i.",
    min_occurrences=200,
    notes="Mitigation direction is inverted relative to formation, as for ICT.",
),
"smc_fvg": dict(
    concept="SMC Fair Value Gap", source="SMC_Concepts_LuxAlgo.pine",
    source_section="2.5", module="signals/smc_signals.py::detect_fvg",
    signals=[("smc_fvg_bullish_formed",1),("smc_fvg_bearish_formed",-1)],
    definition="""
      bar_delta_pct_i = (close_{i-1} - open_{i-1}) / open_{i-1}
      threshold_i     = 2 * cumulative_mean(abs(bar_delta_pct))_i   # if auto
      bullish_i = low_i  > high_{i-2} AND close_{i-1} > high_{i-2}
                  AND bar_delta_pct_i > threshold_i
      bearish_i = high_i < low_{i-2}  AND close_{i-1} < low_{i-2}
                  AND -bar_delta_pct_i > threshold_i
    """,
    params=[("fvg_auto_threshold","bool",True,"true|false","Adaptive vs zero threshold"),
            ("fvg_extend_bars","int",1,"0..10","Display-only in source; no effect here")],
    causal="Uses bars i, i-1, i-2 and an expanding mean over bars <= i.",
    min_occurrences=500,
    notes=("The implementation divides by `open * 100` where the source uses "
           "`/ open * 100`. Both sides of the comparison carry the same 1e-4 "
           "factor, so the test is scale-invariant and results are unaffected; "
           "left as-is to avoid changing published numbers for no benefit."),
),
"smc_equal_highs_lows": dict(
    concept="SMC Equal Highs / Equal Lows", source="SMC_Concepts_LuxAlgo.pine",
    source_section="2.4", module="signals/smc_signals.py::detect_equal_highs_lows",
    signals=[("smc_equal_highs", -1), ("smc_equal_lows", 1)],
    definition="""
      For consecutive confirmed swing highs h_{k-1}, h_k at bar i:
        equal_high_i = abs(h_k - h_{k-1}) < threshold * ATR(atr_len)_i
      Mirror for swing lows.
    """,
    params=[("equal_hl_len","int",3,">=1","Swing lookback"),
            ("equal_hl_threshold","float",0.1,"0.02..0.40","Tolerance as a fraction of ATR"),
            ("equal_hl_atr_len","int",200,"20..400","ATR length")],
    causal="Swing points carry their confirmation lag; ATR is trailing.",
    min_occurrences=100,
    notes=("DIRECTION ASSIGNED EXPLICITLY. Equal highs are resistance with "
           "resting liquidity above -> bearish (-1); equal lows -> bullish (+1). "
           "Neither name contains 'bullish'/'bearish', so the prior substring "
           "heuristic returned direction 0 for both and the backtester coerced "
           "0 to +1 -- scoring equal highs with the wrong sign."),
),
}


def render(key, d):
    lines = [HEADER.format(title=d["concept"]), f'concept: "{d["concept"]}"',
             f'id: {key}', f'source_script: "{d["source"]}"',
             f'source_section: "{d["source_section"]}"',
             f'implementation: "{d["module"]}"', "", "signals:"]
    for name, direction in d["signals"]:
        lines.append(f'  - name: {name}')
        lines.append(f'    direction: {direction:+d}')
    lines += ["", "definition: |"]
    lines += ["  " + ln for ln in textwrap.dedent(d["definition"]).strip("\n").splitlines()]
    lines += ["", "parameters:"]
    if not d["params"]:
        lines.append("  []")
    for name, typ, default, rng, desc in d["params"]:
        lines.append(f'  - name: {name.split()[-1] if " " in name else name}')
        lines.append(f"    type: {typ}")
        lines.append(f'    default: {default}')
        lines.append(f'    allowed_range: "{rng}"')
        if desc:
            lines.append(f'    description: "{desc}"')
    lines += ["", "causality: |"]
    lines += ["  " + ln for ln in textwrap.fill(d["causal"], 74).splitlines()]
    lines += ["", f'expected_min_occurrences: {d["min_occurrences"]}']
    lines += ["", "notes: |"]
    lines += ["  " + ln for ln in textwrap.fill(d["notes"], 74).splitlines()]
    return "\n".join(lines) + "\n"


for key, d in SPECS.items():
    (OUT / f"{key}.yaml").write_text(render(key, d), encoding="utf-8")
    print("wrote", OUT / f"{key}.yaml")

schema = '''# Schema for docs/specs/*.yaml
concept:                  str    # human-readable concept name
id:                       str    # file stem
source_script:            str    # originating Pine file
source_section:           str    # section in docs/concepts_extraction.md
implementation:           str    # module::function that implements it
signals:                         # tradeable event columns produced
  - name:                 str
    direction:            int    # +1 long, -1 short; must match EVENT_REGISTRY
definition:               str    # boolean expression over OHLCV/indicators
parameters:
  - name:                 str
    type:                 str
    default:              any
    allowed_range:        str
    description:          str
causality:                str    # argument that the detector reads no future bar
expected_min_occurrences: int    # universe-wide floor; below this the concept
                                 # is reported but not treated as evidence
notes:                    str
'''
(OUT / "_schema.yaml").write_text(schema, encoding="utf-8")
print("wrote", OUT / "_schema.yaml")
